In [3]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('..')
# import numpy as np
import torch
from equitorch.utils._degrees import order_to_degree_index, degree_to_order_index
import torch_geometric.utils as utils

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
print(order_to_degree_index(0,5))
print(order_to_degree_index(3,5))
print(order_to_degree_index(5,5))

tensor([0, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [5]:
t = torch.ones(1,2,16,3,4)#.reshape(-1,3)
t.shape
# t = torch.ones(16).unsqueeze(-1)

torch.Size([1, 2, 16, 3, 4])

In [6]:
# i = order_to_degree_index(0,3)#.reshape(1,1,-1,1)
# i = i.repeat(2)
# i
# i = torch.tensor([0,1,4,9,16,17,20,25,32])
# i = degree_to_order_index(0,4).unsqueeze(0)#.unsqueeze(-1)#.reshape(1,5,1).repeat(2,1,3)
i = degree_to_order_index(0,4,2)
i

tensor([[[ 0,  1,  4,  9, 16]]])

In [7]:
utils.segment(t,i).shape

RuntimeError: segment_reduce(): Expected axis to be the last dimension of offsets but got 0.

In [8]:
utils.segment(t,i)

RuntimeError: segment_reduce(): Expected axis to be the last dimension of offsets but got 0.